require 'bundler/setup'
require 'pry'
require 'delegate'
require 'rack'
require 'codebreaker'
require 'erb'

require_relative './controller/base_controller'
require_relative './controller/app_controller'
require_relative './router'
require_relative './racker'
